language: node_js

os:
  - linux
  - osx

node_js:
  - 'node'
  - 'lts/*'
  - '9'
  - '8'

script:
  - npm install
  - npm run lint
  - npm run build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
