language: node_js

os:
  - linux
  - osx

node_js:
  - 'node'
  - 'lts/*'
  - '9'
  - '8'

script:
  - npm install
  - npm run lint
  - npm run build

jobs:
  include:
    - stage: deploy
      script: curl -X POST -d {} DEPLOY_HOOK_URL
