language: ruby
script: script/cibuild
cache: bundler
sudo: false
exclude: [vendor]
rvm:
  - 2.4.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev


before_install:
  - gem update --system
  - gem install bundler

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
