language: node_js

node_js:
  - 'stable'
  - 'lts/*'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run lint
  - npm run build
